//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Barcode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Barcode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Barcode", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackColor.
        /// </summary>
        internal static string BarcodeGenerating_BacisBackColor {
            get {
                return ResourceManager.GetString("BarcodeGenerating_BacisBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the background color for the barcode image..
        /// </summary>
        internal static string BarcodeGenerating_BacisBackColorDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_BacisBackColorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptionAlignment.
        /// </summary>
        internal static string BarcodeGenerating_BacisCaptionAlignment {
            get {
                return ResourceManager.GetString("BarcodeGenerating_BacisCaptionAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode caption alignment relative to the barcode..
        /// </summary>
        internal static string BarcodeGenerating_BacisCaptionAlignmentDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_BacisCaptionAlignmentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptionPosition.
        /// </summary>
        internal static string BarcodeGenerating_BacisCaptionPosition {
            get {
                return ResourceManager.GetString("BarcodeGenerating_BacisCaptionPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode caption position relative to the barcode symbol..
        /// </summary>
        internal static string BarcodeGenerating_BacisCaptionPositionDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_BacisCaptionPositionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckSumEnabled.
        /// </summary>
        internal static string BarcodeGenerating_BacisCheckSumEnabled {
            get {
                return ResourceManager.GetString("BarcodeGenerating_BacisCheckSumEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets a value indicating whether a checksum of the barcode will be computed and included in the barcode when applicable..
        /// </summary>
        internal static string BarcodeGenerating_BacisCheckSumEnabledDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_BacisCheckSumEnabledDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeType.
        /// </summary>
        internal static string BarcodeGenerating_BacisCodeType {
            get {
                return ResourceManager.GetString("BarcodeGenerating_BacisCodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of encoding to use when generating the barcode image..
        /// </summary>
        internal static string BarcodeGenerating_BacisCodeTypeDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_BacisCodeTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForeColor.
        /// </summary>
        internal static string BarcodeGenerating_BacisForeColor {
            get {
                return ResourceManager.GetString("BarcodeGenerating_BacisForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the foreground color for the barcode image..
        /// </summary>
        internal static string BarcodeGenerating_BacisForeColorDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_BacisForeColorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bacis Settings.
        /// </summary>
        internal static string BarcodeGenerating_BacisSettings {
            get {
                return ResourceManager.GetString("BarcodeGenerating_BacisSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string BarcodeGenerating_BacisText {
            get {
                return ResourceManager.GetString("BarcodeGenerating_BacisText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value that is encoded as a barcode image..
        /// </summary>
        internal static string BarcodeGenerating_BacisTextDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_BacisTextDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string BarcodeGenerating_BacisType {
            get {
                return ResourceManager.GetString("BarcodeGenerating_BacisType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file type of the barcode image..
        /// </summary>
        internal static string BarcodeGenerating_BacisTypeDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_BacisTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string BarcodeGenerating_Barcode {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BearBar.
        /// </summary>
        internal static string BarcodeGenerating_Code25IntlvBearBar {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Code25IntlvBearBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether or not to display bearer bar to ITF barcode..
        /// </summary>
        internal static string BarcodeGenerating_Code25IntlvBearBarDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Code25IntlvBearBarDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineStroke.
        /// </summary>
        internal static string BarcodeGenerating_Code25IntlvLineStroke {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Code25IntlvLineStroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color of bearer bar..
        /// </summary>
        internal static string BarcodeGenerating_Code25IntlvLineStrokeDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Code25IntlvLineStrokeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineStrokeThickness.
        /// </summary>
        internal static string BarcodeGenerating_Code25IntlvLineStrokeThickness {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Code25IntlvLineStrokeThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The line width of bearer bar..
        /// </summary>
        internal static string BarcodeGenerating_Code25IntlvLineStrokeThicknessDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Code25IntlvLineStrokeThicknessDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code25intlv Settings.
        /// </summary>
        internal static string BarcodeGenerating_Code25IntlvSettings {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Code25IntlvSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string BarcodeGenerating_Code49Group {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Code49Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets groups number..
        /// </summary>
        internal static string BarcodeGenerating_Code49GroupDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Code49GroupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        internal static string BarcodeGenerating_Code49Grouping {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Code49Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets a value indicating whether grouping is set for the barcode..
        /// </summary>
        internal static string BarcodeGenerating_Code49GroupingDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Code49GroupingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code49 Settings.
        /// </summary>
        internal static string BarcodeGenerating_Code49Settings {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Code49Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecc000_140SymbolSize.
        /// </summary>
        internal static string BarcodeGenerating_DataMatrixEcc000_140SymbolSize {
            get {
                return ResourceManager.GetString("BarcodeGenerating_DataMatrixEcc000_140SymbolSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the size of the ECC000-140 symbol..
        /// </summary>
        internal static string BarcodeGenerating_DataMatrixEcc000_140SymbolSizeDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_DataMatrixEcc000_140SymbolSizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecc200EncodingMode.
        /// </summary>
        internal static string BarcodeGenerating_DataMatrixEcc200EncodingMode {
            get {
                return ResourceManager.GetString("BarcodeGenerating_DataMatrixEcc200EncodingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the ECC200 encoding mode..
        /// </summary>
        internal static string BarcodeGenerating_DataMatrixEcc200EncodingModeDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_DataMatrixEcc200EncodingModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecc200SymbolSize.
        /// </summary>
        internal static string BarcodeGenerating_DataMatrixEcc200SymbolSize {
            get {
                return ResourceManager.GetString("BarcodeGenerating_DataMatrixEcc200SymbolSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the size of the ECC200 symbol..
        /// </summary>
        internal static string BarcodeGenerating_DataMatrixEcc200SymbolSizeDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_DataMatrixEcc200SymbolSizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EccMode.
        /// </summary>
        internal static string BarcodeGenerating_DataMatrixEccMode {
            get {
                return ResourceManager.GetString("BarcodeGenerating_DataMatrixEccMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the ECC mode..
        /// </summary>
        internal static string BarcodeGenerating_DataMatrixEccModeDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_DataMatrixEccModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileIdentifier.
        /// </summary>
        internal static string BarcodeGenerating_DataMatrixFileIdentifier {
            get {
                return ResourceManager.GetString("BarcodeGenerating_DataMatrixFileIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the file identifier of a related group of structured append symbols..
        /// </summary>
        internal static string BarcodeGenerating_DataMatrixFileIdentifierDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_DataMatrixFileIdentifierDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataMatrix Settings.
        /// </summary>
        internal static string BarcodeGenerating_DataMatrixSettings {
            get {
                return ResourceManager.GetString("BarcodeGenerating_DataMatrixSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StructuredAppend.
        /// </summary>
        internal static string BarcodeGenerating_DataMatrixStructuredAppend {
            get {
                return ResourceManager.GetString("BarcodeGenerating_DataMatrixStructuredAppend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets a value indicating whether the current symbol is part of structured append symbols..
        /// </summary>
        internal static string BarcodeGenerating_DataMatrixStructuredAppendDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_DataMatrixStructuredAppendDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StructureNumber.
        /// </summary>
        internal static string BarcodeGenerating_DataMatrixStructureNumber {
            get {
                return ResourceManager.GetString("BarcodeGenerating_DataMatrixStructureNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the structure number of current symbol within the structured append symbols..
        /// </summary>
        internal static string BarcodeGenerating_DataMatrixStructureNumberDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_DataMatrixStructureNumberDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string BarcodeGenerating_Description {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarAdjust.
        /// </summary>
        internal static string BarcodeGenerating_Ean128Fnc1BarAdjust {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Ean128Fnc1BarAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the adjustment size by dot..
        /// </summary>
        internal static string BarcodeGenerating_Ean128Fnc1BarAdjustDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Ean128Fnc1BarAdjustDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dpi.
        /// </summary>
        internal static string BarcodeGenerating_Ean128Fnc1Dpi {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Ean128Fnc1Dpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the resolution of the printer..
        /// </summary>
        internal static string BarcodeGenerating_Ean128Fnc1DpiDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Ean128Fnc1DpiDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleSize.
        /// </summary>
        internal static string BarcodeGenerating_Ean128Fnc1ModuleSize {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Ean128Fnc1ModuleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the horizontal size of the barcode module..
        /// </summary>
        internal static string BarcodeGenerating_Ean128Fnc1ModuleSizeDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Ean128Fnc1ModuleSizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ean128Fnc1 Settings.
        /// </summary>
        internal static string BarcodeGenerating_Ean128Fnc1Settings {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Ean128Fnc1Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Barcode.
        /// </summary>
        internal static string BarcodeGenerating_GenerateBarcode {
            get {
                return ResourceManager.GetString("BarcodeGenerating_GenerateBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GS1Composite Settings.
        /// </summary>
        internal static string BarcodeGenerating_GS1CompositeSettings {
            get {
                return ResourceManager.GetString("BarcodeGenerating_GS1CompositeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string BarcodeGenerating_GS1CompositeType {
            get {
                return ResourceManager.GetString("BarcodeGenerating_GS1CompositeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the composite symbol type..
        /// </summary>
        internal static string BarcodeGenerating_GS1CompositeTypeDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_GS1CompositeTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string BarcodeGenerating_GS1CompositeValue {
            get {
                return ResourceManager.GetString("BarcodeGenerating_GS1CompositeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the CCA or CCB character data..
        /// </summary>
        internal static string BarcodeGenerating_GS1CompositeValueDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_GS1CompositeValueDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your browser does not support TIFF images, you can click &lt;a id=&quot;downloadLink&quot;&gt;here&lt;/a&gt; to download it..
        /// </summary>
        internal static string BarcodeGenerating_MessageInfo {
            get {
                return ResourceManager.GetString("BarcodeGenerating_MessageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompactionMode.
        /// </summary>
        internal static string BarcodeGenerating_MicroPDF417CompactionMode {
            get {
                return ResourceManager.GetString("BarcodeGenerating_MicroPDF417CompactionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the CompactionMode..
        /// </summary>
        internal static string BarcodeGenerating_MicroPDF417CompactionModeDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_MicroPDF417CompactionModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileID.
        /// </summary>
        internal static string BarcodeGenerating_MicroPDF417FileID {
            get {
                return ResourceManager.GetString("BarcodeGenerating_MicroPDF417FileID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the file id of structured append symbol..
        /// </summary>
        internal static string BarcodeGenerating_MicroPDF417FileIDDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_MicroPDF417FileIDDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SegmentCount.
        /// </summary>
        internal static string BarcodeGenerating_MicroPDF417SegmentCount {
            get {
                return ResourceManager.GetString("BarcodeGenerating_MicroPDF417SegmentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the segment count of structured append symbol..
        /// </summary>
        internal static string BarcodeGenerating_MicroPDF417SegmentCountDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_MicroPDF417SegmentCountDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SegmentIndex.
        /// </summary>
        internal static string BarcodeGenerating_MicroPDF417SegmentIndex {
            get {
                return ResourceManager.GetString("BarcodeGenerating_MicroPDF417SegmentIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the segment index of structured append symbol..
        /// </summary>
        internal static string BarcodeGenerating_MicroPDF417SegmentIndexDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_MicroPDF417SegmentIndexDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MicroPDF417 Settings.
        /// </summary>
        internal static string BarcodeGenerating_MicroPDF417Settings {
            get {
                return ResourceManager.GetString("BarcodeGenerating_MicroPDF417Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string BarcodeGenerating_MicroPDF417Version {
            get {
                return ResourceManager.GetString("BarcodeGenerating_MicroPDF417Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the symbol version..
        /// </summary>
        internal static string BarcodeGenerating_MicroPDF417VersionDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_MicroPDF417VersionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string BarcodeGenerating_Parameter {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string BarcodeGenerating_Parameters {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string BarcodeGenerating_PDF417Column {
            get {
                return ResourceManager.GetString("BarcodeGenerating_PDF417Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets columns number for the barcode..
        /// </summary>
        internal static string BarcodeGenerating_PDF417ColumnDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_PDF417ColumnDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets row numbers for the barcode..
        /// </summary>
        internal static string BarcodeGenerating_PDF417Desc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_PDF417Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorLevel.
        /// </summary>
        internal static string BarcodeGenerating_PDF417ErrorLevel {
            get {
                return ResourceManager.GetString("BarcodeGenerating_PDF417ErrorLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the error correction level for the barcode..
        /// </summary>
        internal static string BarcodeGenerating_PDF417ErrorLevelDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_PDF417ErrorLevelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        internal static string BarcodeGenerating_PDF417Row {
            get {
                return ResourceManager.GetString("BarcodeGenerating_PDF417Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF417 Settings.
        /// </summary>
        internal static string BarcodeGenerating_PDF417Settings {
            get {
                return ResourceManager.GetString("BarcodeGenerating_PDF417Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string BarcodeGenerating_PDF417Type {
            get {
                return ResourceManager.GetString("BarcodeGenerating_PDF417Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or set the PDF417 barcode&apos;s type..
        /// </summary>
        internal static string BarcodeGenerating_PDF417TypeDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_PDF417TypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string BarcodeGenerating_QRCodeConnection {
            get {
                return ResourceManager.GetString("BarcodeGenerating_QRCodeConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets whether connection is used for the barcode..
        /// </summary>
        internal static string BarcodeGenerating_QRCodeConnectionDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_QRCodeConnectionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionNumber.
        /// </summary>
        internal static string BarcodeGenerating_QRCodeConnectionNumber {
            get {
                return ResourceManager.GetString("BarcodeGenerating_QRCodeConnectionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the connection number for the barcode..
        /// </summary>
        internal static string BarcodeGenerating_QRCodeConnectionNumberDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_QRCodeConnectionNumberDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorLevel.
        /// </summary>
        internal static string BarcodeGenerating_QRCodeErrorLevel {
            get {
                return ResourceManager.GetString("BarcodeGenerating_QRCodeErrorLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the error correction level for the barcode..
        /// </summary>
        internal static string BarcodeGenerating_QRCodeErrorLevelDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_QRCodeErrorLevelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask.
        /// </summary>
        internal static string BarcodeGenerating_QRCodeMask {
            get {
                return ResourceManager.GetString("BarcodeGenerating_QRCodeMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the pattern used for the barcode masking..
        /// </summary>
        internal static string BarcodeGenerating_QRCodeMaskDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_QRCodeMaskDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string BarcodeGenerating_QRCodeModel {
            get {
                return ResourceManager.GetString("BarcodeGenerating_QRCodeModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the QRCode model..
        /// </summary>
        internal static string BarcodeGenerating_QRCodeModelDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_QRCodeModelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRCode Settings.
        /// </summary>
        internal static string BarcodeGenerating_QRCodeSettings {
            get {
                return ResourceManager.GetString("BarcodeGenerating_QRCodeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string BarcodeGenerating_QRCodeVersion {
            get {
                return ResourceManager.GetString("BarcodeGenerating_QRCodeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the QRCode version. Specify any value between 1 and 14 when the Model property is set to Model1 and 1 to 40 for Model2. When -1 is specified, the version most suited to the value is automatically determined..
        /// </summary>
        internal static string BarcodeGenerating_QRCodeVersionDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_QRCodeVersionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Url.
        /// </summary>
        internal static string BarcodeGenerating_RequestUrl {
            get {
                return ResourceManager.GetString("BarcodeGenerating_RequestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowCount.
        /// </summary>
        internal static string BarcodeGenerating_RssExpandedStackedRowCount {
            get {
                return ResourceManager.GetString("BarcodeGenerating_RssExpandedStackedRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the number of stacked rows..
        /// </summary>
        internal static string BarcodeGenerating_RssExpandedStackedRowCountDesc {
            get {
                return ResourceManager.GetString("BarcodeGenerating_RssExpandedStackedRowCountDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RssExpandedStacked Settings.
        /// </summary>
        internal static string BarcodeGenerating_RssExpandedStackedSettings {
            get {
                return ResourceManager.GetString("BarcodeGenerating_RssExpandedStackedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string BarcodeGenerating_Value {
            get {
                return ResourceManager.GetString("BarcodeGenerating_Value", resourceCulture);
            }
        }
    }
}
