//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MVCFlexChart {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MVCFlexChart() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MVCFlexChart", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a MVC FlexChart Box and Whisker series to image file..
        /// </summary>
        internal static string BoxWhisker_Text0 {
            get {
                return ResourceManager.GetString("BoxWhisker_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a MVC bubble FlexChart to image file..
        /// </summary>
        internal static string Bubble_Text0 {
            get {
                return ResourceManager.GetString("Bubble_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a MVC FlexChart ErrorBar series to image file..
        /// </summary>
        internal static string ErrorBar_Text0 {
            get {
                return ResourceManager.GetString("ErrorBar_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorAmount: .
        /// </summary>
        internal static string Error_ErrorAmount {
            get {
                return ResourceManager.GetString("Error_ErrorAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value: .
        /// </summary>
        internal static string Error_Value {
            get {
                return ResourceManager.GetString("Error_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close: .
        /// </summary>
        internal static string FinancialChart_Close {
            get {
                return ResourceManager.GetString("FinancialChart_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: .
        /// </summary>
        internal static string FinancialChart_Date {
            get {
                return ResourceManager.GetString("FinancialChart_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High: .
        /// </summary>
        internal static string FinancialChart_High {
            get {
                return ResourceManager.GetString("FinancialChart_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low: .
        /// </summary>
        internal static string FinancialChart_Low {
            get {
                return ResourceManager.GetString("FinancialChart_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open: .
        /// </summary>
        internal static string FinancialChart_Open {
            get {
                return ResourceManager.GetString("FinancialChart_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a MVC Financial FlexChart to image file..
        /// </summary>
        internal static string FinancialChart_Text0 {
            get {
                return ResourceManager.GetString("FinancialChart_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer (c) .
        /// </summary>
        internal static string HeaderFooter_Footer {
            get {
                return ResourceManager.GetString("HeaderFooter_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales In China In 3 Months.
        /// </summary>
        internal static string HeaderFooter_Header {
            get {
                return ResourceManager.GetString("HeaderFooter_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a MVC FlexChart with header and footer to image file..
        /// </summary>
        internal static string HeaderFooter_Text0 {
            get {
                return ResourceManager.GetString("HeaderFooter_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a MVC FlexChart to image file..
        /// </summary>
        internal static string Index_Text0 {
            get {
                return ResourceManager.GetString("Index_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a MVC FlexChart with different labels to image file..
        /// </summary>
        internal static string Labels_Text0 {
            get {
                return ResourceManager.GetString("Labels_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period:.
        /// </summary>
        internal static string MovingAverage_Period {
            get {
                return ResourceManager.GetString("MovingAverage_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a MVC FlexChart MovingAverage series to image file..
        /// </summary>
        internal static string MovingAverage_Text0 {
            get {
                return ResourceManager.GetString("MovingAverage_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a MVC FlexChart ParametricFunctionSeries to image file..
        /// </summary>
        internal static string ParametricFunctionSeries_Text0 {
            get {
                return ResourceManager.GetString("ParametricFunctionSeries_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order:.
        /// </summary>
        internal static string TrendLine_Order {
            get {
                return ResourceManager.GetString("TrendLine_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Equation:.
        /// </summary>
        internal static string TrendLine_ShowEquation {
            get {
                return ResourceManager.GetString("TrendLine_ShowEquation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a MVC FlexChart TrendLine series to image file..
        /// </summary>
        internal static string TrendLine_Text0 {
            get {
                return ResourceManager.GetString("TrendLine_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a MVC FlexChart Waterfall series to image file..
        /// </summary>
        internal static string Waterfall_Text0 {
            get {
                return ResourceManager.GetString("Waterfall_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a MVC FlexChart YFunctionSeries to image file..
        /// </summary>
        internal static string YFunctionSeries_Text0 {
            get {
                return ResourceManager.GetString("YFunctionSeries_Text0", resourceCulture);
            }
        }
    }
}
