//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Wijmo5FlexChart {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Wijmo5FlexChart() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Wijmo5FlexChart", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gap Width:.
        /// </summary>
        internal static string BoxWhisker_GapWidth {
            get {
                return ResourceManager.GetString("BoxWhisker_GapWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Width:.
        /// </summary>
        internal static string BoxWhisker_GroupWidth {
            get {
                return ResourceManager.GetString("BoxWhisker_GroupWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Quartile Calculation:.
        /// </summary>
        internal static string BoxWhisker_QuartileCalculation {
            get {
                return ResourceManager.GetString("BoxWhisker_QuartileCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotated.
        /// </summary>
        internal static string BoxWhisker_Rotated {
            get {
                return ResourceManager.GetString("BoxWhisker_Rotated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Inner Points.
        /// </summary>
        internal static string BoxWhisker_ShowInnerPoints {
            get {
                return ResourceManager.GetString("BoxWhisker_ShowInnerPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Label.
        /// </summary>
        internal static string BoxWhisker_ShowLabel {
            get {
                return ResourceManager.GetString("BoxWhisker_ShowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Mean Line.
        /// </summary>
        internal static string BoxWhisker_ShowMeanLine {
            get {
                return ResourceManager.GetString("BoxWhisker_ShowMeanLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Mean Marker.
        /// </summary>
        internal static string BoxWhisker_ShowMeanMarker {
            get {
                return ResourceManager.GetString("BoxWhisker_ShowMeanMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Outliers.
        /// </summary>
        internal static string BoxWhisker_ShowOutliers {
            get {
                return ResourceManager.GetString("BoxWhisker_ShowOutliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a Wijmo 5 FlexChart Box and Whisker series to image file..
        /// </summary>
        internal static string BoxWhisker_Text0 {
            get {
                return ResourceManager.GetString("BoxWhisker_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a wijmo5 bubble FlexChart to image file..
        /// </summary>
        internal static string Bubble_Text0 {
            get {
                return ResourceManager.GetString("Bubble_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Type:.
        /// </summary>
        internal static string ErrorBar_ChartType {
            get {
                return ResourceManager.GetString("ErrorBar_ChartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction:.
        /// </summary>
        internal static string ErrorBar_Direction {
            get {
                return ResourceManager.GetString("ErrorBar_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Style:.
        /// </summary>
        internal static string ErrorBar_EndStyle {
            get {
                return ResourceManager.GetString("ErrorBar_EndStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Amount:.
        /// </summary>
        internal static string ErrorBar_ErrorAmount {
            get {
                return ResourceManager.GetString("ErrorBar_ErrorAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotated.
        /// </summary>
        internal static string ErrorBar_Rotated {
            get {
                return ResourceManager.GetString("ErrorBar_Rotated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a Wijmo 5 FlexChart ErrorBar series to image file..
        /// </summary>
        internal static string ErrorBar_Text0 {
            get {
                return ResourceManager.GetString("ErrorBar_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a wijmo5 Financial FlexChart to image file..
        /// </summary>
        internal static string FinancialChart_Text0 {
            get {
                return ResourceManager.GetString("FinancialChart_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer (c) .
        /// </summary>
        internal static string HeaderFooter_Footer {
            get {
                return ResourceManager.GetString("HeaderFooter_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Sales Summary.
        /// </summary>
        internal static string HeaderFooter_Header {
            get {
                return ResourceManager.GetString("HeaderFooter_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a wijmo5 FlexChart with header and footer to image file..
        /// </summary>
        internal static string HeaderFooter_Text0 {
            get {
                return ResourceManager.GetString("HeaderFooter_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a wijmo5 FlexChart to image file..
        /// </summary>
        internal static string Index_Text0 {
            get {
                return ResourceManager.GetString("Index_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Type:.
        /// </summary>
        internal static string Labels_ChartType {
            get {
                return ResourceManager.GetString("Labels_ChartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Position:.
        /// </summary>
        internal static string Labels_LabelPosition {
            get {
                return ResourceManager.GetString("Labels_LabelPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels border:.
        /// </summary>
        internal static string Labels_LabelsBorder {
            get {
                return ResourceManager.GetString("Labels_LabelsBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a wijmo5 FlexChart with different labels to image file..
        /// </summary>
        internal static string Labels_Text0 {
            get {
                return ResourceManager.GetString("Labels_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period:.
        /// </summary>
        internal static string MovingAverage_Period {
            get {
                return ResourceManager.GetString("MovingAverage_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a Wijmo 5 FlexChart MovingAverage series to image file..
        /// </summary>
        internal static string MovingAverage_Text0 {
            get {
                return ResourceManager.GetString("MovingAverage_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string MovingAverage_Type {
            get {
                return ResourceManager.GetString("MovingAverage_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a Wijmo 5 FlexChart ParametricFunctionSeries to image file..
        /// </summary>
        internal static string ParametricFunctionSeries_Text0 {
            get {
                return ResourceManager.GetString("ParametricFunctionSeries_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Type.
        /// </summary>
        internal static string TrendLine_FitType {
            get {
                return ResourceManager.GetString("TrendLine_FitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a Wijmo 5 FlexChart TrendLine series to image file..
        /// </summary>
        internal static string TrendLine_Text0 {
            get {
                return ResourceManager.GetString("TrendLine_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is RelativeData.
        /// </summary>
        internal static string Waterfall_IsRelativeData {
            get {
                return ResourceManager.GetString("Waterfall_IsRelativeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Connector Lines.
        /// </summary>
        internal static string Waterfall_ShowConnectorLines {
            get {
                return ResourceManager.GetString("Waterfall_ShowConnectorLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Intermediate Total.
        /// </summary>
        internal static string Waterfall_ShowIntermediateTotal {
            get {
                return ResourceManager.GetString("Waterfall_ShowIntermediateTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Total.
        /// </summary>
        internal static string Waterfall_ShowTotal {
            get {
                return ResourceManager.GetString("Waterfall_ShowTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a Wijmo 5 FlexChart Waterfall series to image file..
        /// </summary>
        internal static string Waterfall_Text0 {
            get {
                return ResourceManager.GetString("Waterfall_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to export a Wijmo 5 FlexChart YFunctionSeries to image file..
        /// </summary>
        internal static string YFunctionSeries_Text0 {
            get {
                return ResourceManager.GetString("YFunctionSeries_Text0", resourceCulture);
            }
        }
    }
}
