//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiExplorer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataEngine {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataEngine() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApiExplorer.Localization.DataEngine", typeof(DataEngine).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        public static string Analysis_DataSource {
            get {
                return ResourceManager.GetString("Analysis_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source to analyze..
        /// </summary>
        public static string Analysis_DataSourceDesc {
            get {
                return ResourceManager.GetString("Analysis_DataSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Analysis_Description {
            get {
                return ResourceManager.GetString("Analysis_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAnalysis.
        /// </summary>
        public static string Analysis_GetAnalysis {
            get {
                return ResourceManager.GetString("Analysis_GetAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        public static string Analysis_Headers {
            get {
                return ResourceManager.GetString("Analysis_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string Analysis_Parameter {
            get {
                return ResourceManager.GetString("Analysis_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Analysis_Parameters {
            get {
                return ResourceManager.GetString("Analysis_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request URL: .
        /// </summary>
        public static string Analysis_RequestURL {
            get {
                return ResourceManager.GetString("Analysis_RequestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Data.
        /// </summary>
        public static string Analysis_ResponseData {
            get {
                return ResourceManager.GetString("Analysis_ResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Code: .
        /// </summary>
        public static string Analysis_StatusCode {
            get {
                return ResourceManager.GetString("Analysis_StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string Analysis_Token {
            get {
                return ResourceManager.GetString("Analysis_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token of analysis instance..
        /// </summary>
        public static string Analysis_TokenDesc {
            get {
                return ResourceManager.GetString("Analysis_TokenDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Analysis_Value {
            get {
                return ResourceManager.GetString("Analysis_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze.
        /// </summary>
        public static string Analyze_Analyze {
            get {
                return ResourceManager.GetString("Analyze_Analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        public static string Analyze_DataSource {
            get {
                return ResourceManager.GetString("Analyze_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex (100,000 items).
        /// </summary>
        public static string Analyze_DataSource_Complex10 {
            get {
                return ResourceManager.GetString("Analyze_DataSource_Complex10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex (1,000,000 items).
        /// </summary>
        public static string Analyze_DataSource_Complex100 {
            get {
                return ResourceManager.GetString("Analyze_DataSource_Complex100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex (500,000 items).
        /// </summary>
        public static string Analyze_DataSource_Complex50 {
            get {
                return ResourceManager.GetString("Analyze_DataSource_Complex50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSAS (Adventure Works).
        /// </summary>
        public static string Analyze_DataSource_Cube {
            get {
                return ResourceManager.GetString("Analyze_DataSource_Cube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource (100,000 items).
        /// </summary>
        public static string Analyze_DataSource_Dataset10 {
            get {
                return ResourceManager.GetString("Analyze_DataSource_Dataset10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource (1,000,000 items).
        /// </summary>
        public static string Analyze_DataSource_Dataset100 {
            get {
                return ResourceManager.GetString("Analyze_DataSource_Dataset100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource (500,000 items).
        /// </summary>
        public static string Analyze_DataSource_Dataset50 {
            get {
                return ResourceManager.GetString("Analyze_DataSource_Dataset50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a data source.
        /// </summary>
        public static string Analyze_DataSource_None {
            get {
                return ResourceManager.GetString("Analyze_DataSource_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source to analyze..
        /// </summary>
        public static string Analyze_DataSourceDesc {
            get {
                return ResourceManager.GetString("Analyze_DataSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Analyze_Description {
            get {
                return ResourceManager.GetString("Analyze_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        public static string Analyze_Headers {
            get {
                return ResourceManager.GetString("Analyze_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string Analyze_Parameter {
            get {
                return ResourceManager.GetString("Analyze_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Analyze_Parameters {
            get {
                return ResourceManager.GetString("Analyze_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request URL: .
        /// </summary>
        public static string Analyze_RequestURL {
            get {
                return ResourceManager.GetString("Analyze_RequestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Data.
        /// </summary>
        public static string Analyze_ResponseData {
            get {
                return ResourceManager.GetString("Analyze_ResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Code: .
        /// </summary>
        public static string Analyze_StatusCode {
            get {
                return ResourceManager.GetString("Analyze_StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Analyze_Value {
            get {
                return ResourceManager.GetString("Analyze_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Definition.
        /// </summary>
        public static string Analyze_ViewDefinition {
            get {
                return ResourceManager.GetString("Analyze_ViewDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view definition to analyze. For example:&lt;br /&gt;
        ///                    &lt;em class=&quot;codes&quot;&gt;
        ///                        {&lt;br /&gt;
        ///                        &amp;nbsp; fields:[&lt;br /&gt;
        ///                        &amp;nbsp;&amp;nbsp; {&amp;quot;binding&amp;quot;:&amp;quot;Active&amp;quot;,&amp;quot;dataType&amp;quot;:3},&lt;br /&gt;
        ///                        &amp;nbsp;&amp;nbsp; {&amp;quot;binding&amp;quot;:&amp;quot;Country&amp;quot;,&amp;quot;dataType&amp;quot;:1},&lt;br /&gt;
        ///                        &amp;nbsp;&amp;nbsp; {&amp;quot;binding&amp;quot;:&amp;quot;Date&amp;quot;,&amp;quot;dataType&amp;quot;:4},&lt;br /&gt;
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Analyze_ViewDefinitionDesc {
            get {
                return ResourceManager.GetString("Analyze_ViewDefinitionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear_Clear {
            get {
                return ResourceManager.GetString("Clear_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        public static string Clear_DataSource {
            get {
                return ResourceManager.GetString("Clear_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source to analyze..
        /// </summary>
        public static string Clear_DataSourceDesc {
            get {
                return ResourceManager.GetString("Clear_DataSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Clear_Description {
            get {
                return ResourceManager.GetString("Clear_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        public static string Clear_Headers {
            get {
                return ResourceManager.GetString("Clear_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string Clear_Parameter {
            get {
                return ResourceManager.GetString("Clear_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Clear_Parameters {
            get {
                return ResourceManager.GetString("Clear_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request URL: .
        /// </summary>
        public static string Clear_RequestURL {
            get {
                return ResourceManager.GetString("Clear_RequestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Data.
        /// </summary>
        public static string Clear_ResponseData {
            get {
                return ResourceManager.GetString("Clear_ResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Code: .
        /// </summary>
        public static string Clear_StatusCode {
            get {
                return ResourceManager.GetString("Clear_StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string Clear_Token {
            get {
                return ResourceManager.GetString("Clear_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token of analysis instance..
        /// </summary>
        public static string Clear_TokenDesc {
            get {
                return ResourceManager.GetString("Clear_TokenDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Clear_Value {
            get {
                return ResourceManager.GetString("Clear_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        public static string Detail_DataSource {
            get {
                return ResourceManager.GetString("Detail_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex (100,000 items).
        /// </summary>
        public static string Detail_DataSource_Complex10 {
            get {
                return ResourceManager.GetString("Detail_DataSource_Complex10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex (1,000,000 items).
        /// </summary>
        public static string Detail_DataSource_Complex100 {
            get {
                return ResourceManager.GetString("Detail_DataSource_Complex100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex (500,000 items).
        /// </summary>
        public static string Detail_DataSource_Complex50 {
            get {
                return ResourceManager.GetString("Detail_DataSource_Complex50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource (100,000 items).
        /// </summary>
        public static string Detail_DataSource_Dataset10 {
            get {
                return ResourceManager.GetString("Detail_DataSource_Dataset10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource (1,000,000 items).
        /// </summary>
        public static string Detail_DataSource_Dataset100 {
            get {
                return ResourceManager.GetString("Detail_DataSource_Dataset100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource (500,000 items).
        /// </summary>
        public static string Detail_DataSource_Dataset50 {
            get {
                return ResourceManager.GetString("Detail_DataSource_Dataset50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a data source.
        /// </summary>
        public static string Detail_DataSource_none {
            get {
                return ResourceManager.GetString("Detail_DataSource_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source to analyze..
        /// </summary>
        public static string Detail_DataSourceDesc {
            get {
                return ResourceManager.GetString("Detail_DataSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Detail_Description {
            get {
                return ResourceManager.GetString("Detail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Details.
        /// </summary>
        public static string Detail_GetDetails {
            get {
                return ResourceManager.GetString("Detail_GetDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        public static string Detail_Headers {
            get {
                return ResourceManager.GetString("Detail_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Detail_Key {
            get {
                return ResourceManager.GetString("Detail_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the cell via the corresponding value. It is an array object. Firstly, you need add the values of the fields in rowFields in order into keys. Then add the values of the fields in columnFields in order. If some field value is null, JUST add null into array and DO NOT remove it. You should keep the count of the keys array same as the count of the fields in rowFields and columnFields.
        ///                    &lt;br/&gt;
        ///                    For example:
        ///                    &lt;br /&gt;
        ///                    &lt;em class= [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Detail_KeyDesc {
            get {
                return ResourceManager.GetString("Detail_KeyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string Detail_Parameter {
            get {
                return ResourceManager.GetString("Detail_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Detail_Parameters {
            get {
                return ResourceManager.GetString("Detail_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request URL: .
        /// </summary>
        public static string Detail_RequestURL {
            get {
                return ResourceManager.GetString("Detail_RequestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Data.
        /// </summary>
        public static string Detail_ResponseData {
            get {
                return ResourceManager.GetString("Detail_ResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Detail_Skip {
            get {
                return ResourceManager.GetString("Detail_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A positive integer value to specify the start index of the whole detail entries.  If not set, then returns the entries from the first one..
        /// </summary>
        public static string Detail_SkipDesc {
            get {
                return ResourceManager.GetString("Detail_SkipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Code: .
        /// </summary>
        public static string Detail_StatusCode {
            get {
                return ResourceManager.GetString("Detail_StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Detail_Top {
            get {
                return ResourceManager.GetString("Detail_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A positive integer value to specify the count of the returned detail entries. If not set, then returns all entries starting with the skip value..
        /// </summary>
        public static string Detail_TopDesc {
            get {
                return ResourceManager.GetString("Detail_TopDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Detail_Value {
            get {
                return ResourceManager.GetString("Detail_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Definition.
        /// </summary>
        public static string Detail_ViewDefinition {
            get {
                return ResourceManager.GetString("Detail_ViewDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view definition to analyze. For example:&lt;br /&gt;
        ///                    &lt;em class=&quot;codes&quot;&gt;
        ///                        {&lt;br /&gt;
        ///                        &amp;nbsp; fields:[&lt;br /&gt;
        ///                        &amp;nbsp;&amp;nbsp; {&amp;quot;binding&amp;quot;:&amp;quot;Active&amp;quot;,&amp;quot;dataType&amp;quot;:3},&lt;br /&gt;
        ///                        &amp;nbsp;&amp;nbsp; {&amp;quot;binding&amp;quot;:&amp;quot;Country&amp;quot;,&amp;quot;dataType&amp;quot;:1},&lt;br /&gt;
        ///                        &amp;nbsp;&amp;nbsp; {&amp;quot;binding&amp;quot;:&amp;quot;Date&amp;quot;,&amp;quot;dataType&amp;quot;:4},&lt;br /&gt;
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Detail_ViewDefinitionDesc {
            get {
                return ResourceManager.GetString("Detail_ViewDefinitionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        public static string Fields_DataSource {
            get {
                return ResourceManager.GetString("Fields_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex (100,000 items).
        /// </summary>
        public static string Fields_DataSource_Complex10 {
            get {
                return ResourceManager.GetString("Fields_DataSource_Complex10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex (1,000,000 items).
        /// </summary>
        public static string Fields_DataSource_Complex100 {
            get {
                return ResourceManager.GetString("Fields_DataSource_Complex100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex (500,000 items).
        /// </summary>
        public static string Fields_DataSource_Complex50 {
            get {
                return ResourceManager.GetString("Fields_DataSource_Complex50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSAS (Adventure Works).
        /// </summary>
        public static string Fields_DataSource_Cube {
            get {
                return ResourceManager.GetString("Fields_DataSource_Cube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource (100,000 items).
        /// </summary>
        public static string Fields_DataSource_Dataset10 {
            get {
                return ResourceManager.GetString("Fields_DataSource_Dataset10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource (1,000,000 items).
        /// </summary>
        public static string Fields_DataSource_Dataset100 {
            get {
                return ResourceManager.GetString("Fields_DataSource_Dataset100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource (500,000 items).
        /// </summary>
        public static string Fields_DataSource_Dataset50 {
            get {
                return ResourceManager.GetString("Fields_DataSource_Dataset50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected&quot;&gt;Select a data source.
        /// </summary>
        public static string Fields_DataSource_None {
            get {
                return ResourceManager.GetString("Fields_DataSource_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source to get the fields information..
        /// </summary>
        public static string Fields_DataSourceDesc {
            get {
                return ResourceManager.GetString("Fields_DataSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Fields_Description {
            get {
                return ResourceManager.GetString("Fields_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Fields.
        /// </summary>
        public static string Fields_GetFields {
            get {
                return ResourceManager.GetString("Fields_GetFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        public static string Fields_Headers {
            get {
                return ResourceManager.GetString("Fields_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string Fields_Parameter {
            get {
                return ResourceManager.GetString("Fields_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Fields_Parameters {
            get {
                return ResourceManager.GetString("Fields_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request URL: .
        /// </summary>
        public static string Fields_RequestURL {
            get {
                return ResourceManager.GetString("Fields_RequestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Data.
        /// </summary>
        public static string Fields_ResponseData {
            get {
                return ResourceManager.GetString("Fields_ResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Code: .
        /// </summary>
        public static string Fields_StatusCode {
            get {
                return ResourceManager.GetString("Fields_StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Fields_Value {
            get {
                return ResourceManager.GetString("Fields_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        public static string RawData_DataSource {
            get {
                return ResourceManager.GetString("RawData_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex (100,000 items).
        /// </summary>
        public static string RawData_DataSource_Complex10 {
            get {
                return ResourceManager.GetString("RawData_DataSource_Complex10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex (1,000,000 items).
        /// </summary>
        public static string RawData_DataSource_Complex100 {
            get {
                return ResourceManager.GetString("RawData_DataSource_Complex100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex (500,000 items).
        /// </summary>
        public static string RawData_DataSource_Complex50 {
            get {
                return ResourceManager.GetString("RawData_DataSource_Complex50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource (100,000 items).
        /// </summary>
        public static string RawData_DataSource_Dataset10 {
            get {
                return ResourceManager.GetString("RawData_DataSource_Dataset10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource (1,000,000 items).
        /// </summary>
        public static string RawData_DataSource_Dataset100 {
            get {
                return ResourceManager.GetString("RawData_DataSource_Dataset100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource (500,000 items).
        /// </summary>
        public static string RawData_DataSource_Dataset50 {
            get {
                return ResourceManager.GetString("RawData_DataSource_Dataset50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a data source.
        /// </summary>
        public static string RawData_DataSource_None {
            get {
                return ResourceManager.GetString("RawData_DataSource_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source to analyze..
        /// </summary>
        public static string RawData_DataSourceDesc {
            get {
                return ResourceManager.GetString("RawData_DataSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string RawData_Description {
            get {
                return ResourceManager.GetString("RawData_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Raw Data.
        /// </summary>
        public static string RawData_GetRawData {
            get {
                return ResourceManager.GetString("RawData_GetRawData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        public static string RawData_Headers {
            get {
                return ResourceManager.GetString("RawData_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string RawData_Parameter {
            get {
                return ResourceManager.GetString("RawData_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string RawData_Parameters {
            get {
                return ResourceManager.GetString("RawData_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request URL: .
        /// </summary>
        public static string RawData_RequestURL {
            get {
                return ResourceManager.GetString("RawData_RequestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Data.
        /// </summary>
        public static string RawData_ResponseData {
            get {
                return ResourceManager.GetString("RawData_ResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string RawData_Skip {
            get {
                return ResourceManager.GetString("RawData_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A positive integer value to specify the start index of the whole raw data.  If not set, then returns the entries from the first one..
        /// </summary>
        public static string RawData_SkipDesc {
            get {
                return ResourceManager.GetString("RawData_SkipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Code: .
        /// </summary>
        public static string RawData_StatusCode {
            get {
                return ResourceManager.GetString("RawData_StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string RawData_Top {
            get {
                return ResourceManager.GetString("RawData_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A positive integer value to specify the count of the returned raw data. If not set, then returns all entries starting with the skip value..
        /// </summary>
        public static string RawData_TopDesc {
            get {
                return ResourceManager.GetString("RawData_TopDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string RawData_Value {
            get {
                return ResourceManager.GetString("RawData_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        public static string Result_DataSource {
            get {
                return ResourceManager.GetString("Result_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source to analyze..
        /// </summary>
        public static string Result_DataSourceDesc {
            get {
                return ResourceManager.GetString("Result_DataSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Result_Description {
            get {
                return ResourceManager.GetString("Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ResultData.
        /// </summary>
        public static string Result_GetResultData {
            get {
                return ResourceManager.GetString("Result_GetResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        public static string Result_Headers {
            get {
                return ResourceManager.GetString("Result_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string Result_Parameter {
            get {
                return ResourceManager.GetString("Result_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Result_Parameters {
            get {
                return ResourceManager.GetString("Result_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request URL: .
        /// </summary>
        public static string Result_RequestURL {
            get {
                return ResourceManager.GetString("Result_RequestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Data.
        /// </summary>
        public static string Result_ResponseData {
            get {
                return ResourceManager.GetString("Result_ResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Code: .
        /// </summary>
        public static string Result_StatusCode {
            get {
                return ResourceManager.GetString("Result_StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string Result_Token {
            get {
                return ResourceManager.GetString("Result_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token of analysis instance..
        /// </summary>
        public static string Result_TokenDesc {
            get {
                return ResourceManager.GetString("Result_TokenDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Result_Value {
            get {
                return ResourceManager.GetString("Result_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        public static string Status_DataSource {
            get {
                return ResourceManager.GetString("Status_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source to analyze..
        /// </summary>
        public static string Status_DataSourceDesc {
            get {
                return ResourceManager.GetString("Status_DataSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Status_Description {
            get {
                return ResourceManager.GetString("Status_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Status.
        /// </summary>
        public static string Status_GetStatus {
            get {
                return ResourceManager.GetString("Status_GetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        public static string Status_Headers {
            get {
                return ResourceManager.GetString("Status_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string Status_Parameter {
            get {
                return ResourceManager.GetString("Status_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Status_Parameters {
            get {
                return ResourceManager.GetString("Status_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request URL: .
        /// </summary>
        public static string Status_RequestURL {
            get {
                return ResourceManager.GetString("Status_RequestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Data.
        /// </summary>
        public static string Status_ResponseData {
            get {
                return ResourceManager.GetString("Status_ResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Code: .
        /// </summary>
        public static string Status_StatusCode {
            get {
                return ResourceManager.GetString("Status_StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string Status_Token {
            get {
                return ResourceManager.GetString("Status_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token of analysis instance..
        /// </summary>
        public static string Status_TokenDesc {
            get {
                return ResourceManager.GetString("Status_TokenDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Status_Value {
            get {
                return ResourceManager.GetString("Status_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        public static string UniqueValues_DataSource {
            get {
                return ResourceManager.GetString("UniqueValues_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex (100,000 items).
        /// </summary>
        public static string UniqueValues_DataSource_Complex10 {
            get {
                return ResourceManager.GetString("UniqueValues_DataSource_Complex10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex (1,000,000 items).
        /// </summary>
        public static string UniqueValues_DataSource_Complex100 {
            get {
                return ResourceManager.GetString("UniqueValues_DataSource_Complex100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex (500,000 items).
        /// </summary>
        public static string UniqueValues_DataSource_Complex50 {
            get {
                return ResourceManager.GetString("UniqueValues_DataSource_Complex50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource (100,000 items).
        /// </summary>
        public static string UniqueValues_DataSource_Dataset10 {
            get {
                return ResourceManager.GetString("UniqueValues_DataSource_Dataset10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource (1,000,000 items).
        /// </summary>
        public static string UniqueValues_DataSource_Dataset100 {
            get {
                return ResourceManager.GetString("UniqueValues_DataSource_Dataset100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource (500,000 items).
        /// </summary>
        public static string UniqueValues_DataSource_Dataset50 {
            get {
                return ResourceManager.GetString("UniqueValues_DataSource_Dataset50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a data source.
        /// </summary>
        public static string UniqueValues_DataSource_None {
            get {
                return ResourceManager.GetString("UniqueValues_DataSource_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source to analyze..
        /// </summary>
        public static string UniqueValues_DataSourceDesc {
            get {
                return ResourceManager.GetString("UniqueValues_DataSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string UniqueValues_Description {
            get {
                return ResourceManager.GetString("UniqueValues_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string UniqueValues_Field {
            get {
                return ResourceManager.GetString("UniqueValues_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field to get the unique values for.
        ///                    &lt;br /&gt;
        ///                    For example:
        ///                    &lt;br /&gt;
        ///                    &lt;em class=&quot;codes&quot;&gt;
        ///                        Product
        ///                    &lt;/em&gt;.
        /// </summary>
        public static string UniqueValues_FieldDesc {
            get {
                return ResourceManager.GetString("UniqueValues_FieldDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get UnqiueValues.
        /// </summary>
        public static string UniqueValues_GetUnqiueValues {
            get {
                return ResourceManager.GetString("UniqueValues_GetUnqiueValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        public static string UniqueValues_Headers {
            get {
                return ResourceManager.GetString("UniqueValues_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string UniqueValues_Parameter {
            get {
                return ResourceManager.GetString("UniqueValues_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string UniqueValues_Parameters {
            get {
                return ResourceManager.GetString("UniqueValues_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request URL: .
        /// </summary>
        public static string UniqueValues_RequestURL {
            get {
                return ResourceManager.GetString("UniqueValues_RequestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Data.
        /// </summary>
        public static string UniqueValues_ResponseData {
            get {
                return ResourceManager.GetString("UniqueValues_ResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Code: .
        /// </summary>
        public static string UniqueValues_StatusCode {
            get {
                return ResourceManager.GetString("UniqueValues_StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string UniqueValues_Value {
            get {
                return ResourceManager.GetString("UniqueValues_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Definition.
        /// </summary>
        public static string UniqueValues_ViewDefinition {
            get {
                return ResourceManager.GetString("UniqueValues_ViewDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view definition to analyze. For example:&lt;br /&gt;
        ///                    &lt;em class=&quot;codes&quot;&gt;
        ///                        {&lt;br /&gt;
        ///                        &amp;nbsp; fields:[&lt;br /&gt;
        ///                        &amp;nbsp;&amp;nbsp; {&amp;quot;binding&amp;quot;:&amp;quot;Active&amp;quot;,&amp;quot;dataType&amp;quot;:3},&lt;br /&gt;
        ///                        &amp;nbsp;&amp;nbsp; {&amp;quot;binding&amp;quot;:&amp;quot;Country&amp;quot;,&amp;quot;dataType&amp;quot;:1},&lt;br /&gt;
        ///                        &amp;nbsp;&amp;nbsp; {&amp;quot;binding&amp;quot;:&amp;quot;Date&amp;quot;,&amp;quot;dataType&amp;quot;:4},&lt;br /&gt;
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UniqueValues_ViewDefinitionDesc {
            get {
                return ResourceManager.GetString("UniqueValues_ViewDefinitionDesc", resourceCulture);
            }
        }
    }
}
