//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiExplorer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Pdf {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pdf() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApiExplorer.Localization.Pdf", typeof(Pdf).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PdfExportGET_Description {
            get {
                return ResourceManager.GetString("PdfExportGET_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string PdfExportGET_Export {
            get {
                return ResourceManager.GetString("PdfExportGET_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Options.
        /// </summary>
        public static string PdfExportGET_ExportOptions {
            get {
                return ResourceManager.GetString("PdfExportGET_ExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The export options, please see the response of &lt;strong&gt;SupportedFormats&lt;/strong&gt; action. E.g:&lt;br /&gt; outputRange=1&amp;amp;... .
        /// </summary>
        public static string PdfExportGET_ExportOptionsText {
            get {
                return ResourceManager.GetString("PdfExportGET_ExportOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string PdfExportGET_Format {
            get {
                return ResourceManager.GetString("PdfExportGET_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supported formats, please see the response of &lt;strong&gt;SupportedFormats&lt;/strong&gt; action..
        /// </summary>
        public static string PdfExportGET_FormatText {
            get {
                return ResourceManager.GetString("PdfExportGET_FormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        public static string PdfExportGET_Headers {
            get {
                return ResourceManager.GetString("PdfExportGET_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string PdfExportGET_Parameter {
            get {
                return ResourceManager.GetString("PdfExportGET_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string PdfExportGET_Parameters {
            get {
                return ResourceManager.GetString("PdfExportGET_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf Path.
        /// </summary>
        public static string PdfExportGET_PdfPath {
            get {
                return ResourceManager.GetString("PdfExportGET_PdfPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pdf file that storage manager can recognize..
        /// </summary>
        public static string PdfExportGET_PdfPathText {
            get {
                return ResourceManager.GetString("PdfExportGET_PdfPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request URL: .
        /// </summary>
        public static string PdfExportGET_RequestURL {
            get {
                return ResourceManager.GetString("PdfExportGET_RequestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string PdfExportGET_Value {
            get {
                return ResourceManager.GetString("PdfExportGET_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PdfExportPOST_Description {
            get {
                return ResourceManager.GetString("PdfExportPOST_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string PdfExportPOST_Export {
            get {
                return ResourceManager.GetString("PdfExportPOST_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Options.
        /// </summary>
        public static string PdfExportPOST_ExportOptions {
            get {
                return ResourceManager.GetString("PdfExportPOST_ExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The export options, please see the response of &lt;strong&gt;SupportedFormats&lt;/strong&gt; action. E.g:&lt;br /&gt; outputRange=1&amp;amp;... .
        /// </summary>
        public static string PdfExportPOST_ExportOptionsText {
            get {
                return ResourceManager.GetString("PdfExportPOST_ExportOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string PdfExportPOST_Format {
            get {
                return ResourceManager.GetString("PdfExportPOST_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supported formats, please see the response of &lt;strong&gt;SupportedFormats&lt;/strong&gt; action..
        /// </summary>
        public static string PdfExportPOST_FormatText {
            get {
                return ResourceManager.GetString("PdfExportPOST_FormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        public static string PdfExportPOST_Headers {
            get {
                return ResourceManager.GetString("PdfExportPOST_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string PdfExportPOST_Parameter {
            get {
                return ResourceManager.GetString("PdfExportPOST_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string PdfExportPOST_Parameters {
            get {
                return ResourceManager.GetString("PdfExportPOST_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf Path.
        /// </summary>
        public static string PdfExportPOST_PdfPath {
            get {
                return ResourceManager.GetString("PdfExportPOST_PdfPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pdf file that storage manager can recognize..
        /// </summary>
        public static string PdfExportPOST_PdfPathText {
            get {
                return ResourceManager.GetString("PdfExportPOST_PdfPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request URL: .
        /// </summary>
        public static string PdfExportPOST_RequestURL {
            get {
                return ResourceManager.GetString("PdfExportPOST_RequestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string PdfExportPOST_Value {
            get {
                return ResourceManager.GetString("PdfExportPOST_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PdfFeaturesGET_Description {
            get {
                return ResourceManager.GetString("PdfFeaturesGET_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Features.
        /// </summary>
        public static string PdfFeaturesGET_GetFeatures {
            get {
                return ResourceManager.GetString("PdfFeaturesGET_GetFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        public static string PdfFeaturesGET_Headers {
            get {
                return ResourceManager.GetString("PdfFeaturesGET_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string PdfFeaturesGET_Parameter {
            get {
                return ResourceManager.GetString("PdfFeaturesGET_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string PdfFeaturesGET_Parameters {
            get {
                return ResourceManager.GetString("PdfFeaturesGET_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf Path.
        /// </summary>
        public static string PdfFeaturesGET_PdfPath {
            get {
                return ResourceManager.GetString("PdfFeaturesGET_PdfPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pdf file that storage manager can recognize..
        /// </summary>
        public static string PdfFeaturesGET_PdfPathText {
            get {
                return ResourceManager.GetString("PdfFeaturesGET_PdfPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request URL: .
        /// </summary>
        public static string PdfFeaturesGET_RequestURL {
            get {
                return ResourceManager.GetString("PdfFeaturesGET_RequestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Data.
        /// </summary>
        public static string PdfFeaturesGET_ResponseData {
            get {
                return ResourceManager.GetString("PdfFeaturesGET_ResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Code: .
        /// </summary>
        public static string PdfFeaturesGET_StatusCode {
            get {
                return ResourceManager.GetString("PdfFeaturesGET_StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string PdfFeaturesGET_Value {
            get {
                return ResourceManager.GetString("PdfFeaturesGET_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PdfInfoGET_Description {
            get {
                return ResourceManager.GetString("PdfInfoGET_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Info.
        /// </summary>
        public static string PdfInfoGET_GetInfo {
            get {
                return ResourceManager.GetString("PdfInfoGET_GetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        public static string PdfInfoGET_Headers {
            get {
                return ResourceManager.GetString("PdfInfoGET_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string PdfInfoGET_Parameter {
            get {
                return ResourceManager.GetString("PdfInfoGET_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string PdfInfoGET_Parameters {
            get {
                return ResourceManager.GetString("PdfInfoGET_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf Path.
        /// </summary>
        public static string PdfInfoGET_PdfPath {
            get {
                return ResourceManager.GetString("PdfInfoGET_PdfPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pdf file that storage manager can recognize..
        /// </summary>
        public static string PdfInfoGET_PdfPathText {
            get {
                return ResourceManager.GetString("PdfInfoGET_PdfPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request URL: .
        /// </summary>
        public static string PdfInfoGET_RequestURL {
            get {
                return ResourceManager.GetString("PdfInfoGET_RequestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Data.
        /// </summary>
        public static string PdfInfoGET_ResponseData {
            get {
                return ResourceManager.GetString("PdfInfoGET_ResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Code: .
        /// </summary>
        public static string PdfInfoGET_StatusCode {
            get {
                return ResourceManager.GetString("PdfInfoGET_StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string PdfInfoGET_Value {
            get {
                return ResourceManager.GetString("PdfInfoGET_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PdfSearchGET_Description {
            get {
                return ResourceManager.GetString("PdfSearchGET_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        public static string PdfSearchGET_Headers {
            get {
                return ResourceManager.GetString("PdfSearchGET_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Case.
        /// </summary>
        public static string PdfSearchGET_MatchCase {
            get {
                return ResourceManager.GetString("PdfSearchGET_MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A boolean value indicates if search the value with case sensitive..
        /// </summary>
        public static string PdfSearchGET_MatchCaseText {
            get {
                return ResourceManager.GetString("PdfSearchGET_MatchCaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string PdfSearchGET_Parameter {
            get {
                return ResourceManager.GetString("PdfSearchGET_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string PdfSearchGET_Parameters {
            get {
                return ResourceManager.GetString("PdfSearchGET_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf Path.
        /// </summary>
        public static string PdfSearchGET_PdfPath {
            get {
                return ResourceManager.GetString("PdfSearchGET_PdfPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pdf file that storage manager can recognize..
        /// </summary>
        public static string PdfSearchGET_PdfPathText {
            get {
                return ResourceManager.GetString("PdfSearchGET_PdfPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request URL: .
        /// </summary>
        public static string PdfSearchGET_RequestURL {
            get {
                return ResourceManager.GetString("PdfSearchGET_RequestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Data.
        /// </summary>
        public static string PdfSearchGET_ResponseData {
            get {
                return ResourceManager.GetString("PdfSearchGET_ResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string PdfSearchGET_Search {
            get {
                return ResourceManager.GetString("PdfSearchGET_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Scope.
        /// </summary>
        public static string PdfSearchGET_SearchScope {
            get {
                return ResourceManager.GetString("PdfSearchGET_SearchScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To the end of the document.
        /// </summary>
        public static string PdfSearchGET_SearchScope_EndOfDocument {
            get {
                return ResourceManager.GetString("PdfSearchGET_SearchScope_EndOfDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till the first occurrence is found.
        /// </summary>
        public static string PdfSearchGET_SearchScope_FirstOccurrence {
            get {
                return ResourceManager.GetString("PdfSearchGET_SearchScope_FirstOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Within the specified page only.
        /// </summary>
        public static string PdfSearchGET_SearchScope_SinglePage {
            get {
                return ResourceManager.GetString("PdfSearchGET_SearchScope_SinglePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The whole document.
        /// </summary>
        public static string PdfSearchGET_SearchScope_WholeDocument {
            get {
                return ResourceManager.GetString("PdfSearchGET_SearchScope_WholeDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search scope..
        /// </summary>
        public static string PdfSearchGET_SearchScopeText {
            get {
                return ResourceManager.GetString("PdfSearchGET_SearchScopeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Text.
        /// </summary>
        public static string PdfSearchGET_SearchText {
            get {
                return ResourceManager.GetString("PdfSearchGET_SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value which is used to search..
        /// </summary>
        public static string PdfSearchGET_SearchTextText {
            get {
                return ResourceManager.GetString("PdfSearchGET_SearchTextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Page Index.
        /// </summary>
        public static string PdfSearchGET_StartPageIndex {
            get {
                return ResourceManager.GetString("PdfSearchGET_StartPageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-based index of the first page to search..
        /// </summary>
        public static string PdfSearchGET_StartPageIndexText {
            get {
                return ResourceManager.GetString("PdfSearchGET_StartPageIndexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Code: .
        /// </summary>
        public static string PdfSearchGET_StatusCode {
            get {
                return ResourceManager.GetString("PdfSearchGET_StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string PdfSearchGET_Value {
            get {
                return ResourceManager.GetString("PdfSearchGET_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole Word.
        /// </summary>
        public static string PdfSearchGET_WholeWord {
            get {
                return ResourceManager.GetString("PdfSearchGET_WholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A boolean value indicates if search the value with matching a whole word..
        /// </summary>
        public static string PdfSearchGET_WholeWordText {
            get {
                return ResourceManager.GetString("PdfSearchGET_WholeWordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PdfStatusGET_Description {
            get {
                return ResourceManager.GetString("PdfStatusGET_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Status.
        /// </summary>
        public static string PdfStatusGET_GetStatus {
            get {
                return ResourceManager.GetString("PdfStatusGET_GetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        public static string PdfStatusGET_Headers {
            get {
                return ResourceManager.GetString("PdfStatusGET_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string PdfStatusGET_Parameter {
            get {
                return ResourceManager.GetString("PdfStatusGET_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string PdfStatusGET_Parameters {
            get {
                return ResourceManager.GetString("PdfStatusGET_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf Path.
        /// </summary>
        public static string PdfStatusGET_PdfPath {
            get {
                return ResourceManager.GetString("PdfStatusGET_PdfPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pdf file that storage manager can recognize..
        /// </summary>
        public static string PdfStatusGET_PdfPathText {
            get {
                return ResourceManager.GetString("PdfStatusGET_PdfPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request URL: .
        /// </summary>
        public static string PdfStatusGET_RequestURL {
            get {
                return ResourceManager.GetString("PdfStatusGET_RequestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Data.
        /// </summary>
        public static string PdfStatusGET_ResponseData {
            get {
                return ResourceManager.GetString("PdfStatusGET_ResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Code: .
        /// </summary>
        public static string PdfStatusGET_StatusCode {
            get {
                return ResourceManager.GetString("PdfStatusGET_StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string PdfStatusGET_Value {
            get {
                return ResourceManager.GetString("PdfStatusGET_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PdfSupportedFormatsGET_Description {
            get {
                return ResourceManager.GetString("PdfSupportedFormatsGET_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Supported Formats.
        /// </summary>
        public static string PdfSupportedFormatsGET_GetSupportedFormats {
            get {
                return ResourceManager.GetString("PdfSupportedFormatsGET_GetSupportedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        public static string PdfSupportedFormatsGET_Headers {
            get {
                return ResourceManager.GetString("PdfSupportedFormatsGET_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string PdfSupportedFormatsGET_Parameter {
            get {
                return ResourceManager.GetString("PdfSupportedFormatsGET_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string PdfSupportedFormatsGET_Parameters {
            get {
                return ResourceManager.GetString("PdfSupportedFormatsGET_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf Path.
        /// </summary>
        public static string PdfSupportedFormatsGET_PdfPath {
            get {
                return ResourceManager.GetString("PdfSupportedFormatsGET_PdfPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pdf file that storage manager can recognize..
        /// </summary>
        public static string PdfSupportedFormatsGET_PdfPathText {
            get {
                return ResourceManager.GetString("PdfSupportedFormatsGET_PdfPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request URL: .
        /// </summary>
        public static string PdfSupportedFormatsGET_RequestURL {
            get {
                return ResourceManager.GetString("PdfSupportedFormatsGET_RequestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Data.
        /// </summary>
        public static string PdfSupportedFormatsGET_ResponseData {
            get {
                return ResourceManager.GetString("PdfSupportedFormatsGET_ResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Code: .
        /// </summary>
        public static string PdfSupportedFormatsGET_StatusCode {
            get {
                return ResourceManager.GetString("PdfSupportedFormatsGET_StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string PdfSupportedFormatsGET_Value {
            get {
                return ResourceManager.GetString("PdfSupportedFormatsGET_Value", resourceCulture);
            }
        }
    }
}
