//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiExplorer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApiExplorer.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string ControlLayout_Documentation {
            get {
                return ResourceManager.GetString("ControlLayout_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string ControlLayout_Sample {
            get {
                return ResourceManager.GetString("ControlLayout_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string ControlLayout_Source {
            get {
                return ResourceManager.GetString("ControlLayout_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ControlList_Description {
            get {
                return ResourceManager.GetString("ControlList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Status Code.
        /// </summary>
        public static string ControlList_HTTPStatusCode {
            get {
                return ResourceManager.GetString("ControlList_HTTPStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string ControlList_Reason {
            get {
                return ResourceManager.GetString("ControlList_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Messages.
        /// </summary>
        public static string ControlList_ResponseMessages {
            get {
                return ResourceManager.GetString("ControlList_ResponseMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Schema.
        /// </summary>
        public static string ControlList_ResponseSchema {
            get {
                return ResourceManager.GetString("ControlList_ResponseSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string ControlsNav_Features {
            get {
                return ResourceManager.GetString("ControlsNav_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string CultureChinese {
            get {
                return ResourceManager.GetString("CultureChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string CultureDutch {
            get {
                return ResourceManager.GetString("CultureDutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string CultureEnglish {
            get {
                return ResourceManager.GetString("CultureEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string CultureFrench {
            get {
                return ResourceManager.GetString("CultureFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string CultureGerman {
            get {
                return ResourceManager.GetString("CultureGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string CultureItalian {
            get {
                return ResourceManager.GetString("CultureItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string CultureJapanese {
            get {
                return ResourceManager.GetString("CultureJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        public static string CultureKorean {
            get {
                return ResourceManager.GetString("CultureKorean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string CultureSpanish {
            get {
                return ResourceManager.GetString("CultureSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string FlexGridOptions_Export {
            get {
                return ResourceManager.GetString("FlexGridOptions_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Format:.
        /// </summary>
        public static string FlexGridOptions_ExportFormat {
            get {
                return ResourceManager.GetString("FlexGridOptions_ExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export &amp; Import.
        /// </summary>
        public static string FlexGridOptions_ExportImport {
            get {
                return ResourceManager.GetString("FlexGridOptions_ExportImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Name :.
        /// </summary>
        public static string FlexGridOptions_ExportName {
            get {
                return ResourceManager.GetString("FlexGridOptions_ExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string FlexGridOptions_ExportText {
            get {
                return ResourceManager.GetString("FlexGridOptions_ExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string FlexGridOptions_Import {
            get {
                return ResourceManager.GetString("FlexGridOptions_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string FlexGridOptions_ImportText {
            get {
                return ResourceManager.GetString("FlexGridOptions_ImportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncludeColumnHeaders:.
        /// </summary>
        public static string FlexGridOptions_IncludeColumnHeaders {
            get {
                return ResourceManager.GetString("FlexGridOptions_IncludeColumnHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnlyCurrentPage:.
        /// </summary>
        public static string FlexGridOptions_OnlyCurrentPage {
            get {
                return ResourceManager.GetString("FlexGridOptions_OnlyCurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/css/gcicons.css.
        /// </summary>
        public static string GcIconsCssPath {
            get {
                return ResourceManager.GetString("GcIconsCssPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ImageExportOptions_Export {
            get {
                return ResourceManager.GetString("ImageExportOptions_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Format :.
        /// </summary>
        public static string ImageExportOptions_ExportFormat {
            get {
                return ResourceManager.GetString("ImageExportOptions_ExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ImageExportOptions_ExportText {
            get {
                return ResourceManager.GetString("ImageExportOptions_ExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height :.
        /// </summary>
        public static string ImageExportOptions_Height {
            get {
                return ResourceManager.GetString("ImageExportOptions_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width :.
        /// </summary>
        public static string ImageExportOptions_Width {
            get {
                return ResourceManager.GetString("ImageExportOptions_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComponentOne.
        /// </summary>
        public static string Layout_ComponentOne {
            get {
                return ResourceManager.GetString("Layout_ComponentOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.grapecity.com/.
        /// </summary>
        public static string Layout_GrapeCityUrl {
            get {
                return ResourceManager.GetString("Layout_GrapeCityUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrapeCity, Inc. All Rights Reserved..
        /// </summary>
        public static string Layout_License1 {
            get {
                return ResourceManager.GetString("Layout_License1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All product and company names here in may be trademarks of their respective owners..
        /// </summary>
        public static string Layout_License2 {
            get {
                return ResourceManager.GetString("Layout_License2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET Web API Explorer.
        /// </summary>
        public static string Layout_LongTitle {
            get {
                return ResourceManager.GetString("Layout_LongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.grapecity.com/en/webapi/.
        /// </summary>
        public static string Layout_ProductUrl {
            get {
                return ResourceManager.GetString("Layout_ProductUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web API Explorer.
        /// </summary>
        public static string Layout_ShortTitle {
            get {
                return ResourceManager.GetString("Layout_ShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you seen this? C1Studio Web API.
        /// </summary>
        public static string Layout_TwitterText {
            get {
                return ResourceManager.GetString("Layout_TwitterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string SiteNav_About {
            get {
                return ResourceManager.GetString("SiteNav_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.grapecity.com/en/webapi/.
        /// </summary>
        public static string SiteNav_AboutUrl {
            get {
                return ResourceManager.GetString("SiteNav_AboutUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREE TRIAL.
        /// </summary>
        public static string SiteNav_FreeTrial {
            get {
                return ResourceManager.GetString("SiteNav_FreeTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.grapecity.com/en/download/componentone-studio.
        /// </summary>
        public static string SiteNav_FreeTrialUrl {
            get {
                return ResourceManager.GetString("SiteNav_FreeTrialUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string SiteNav_Pricing {
            get {
                return ResourceManager.GetString("SiteNav_Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.grapecity.com/en/pricing.
        /// </summary>
        public static string SiteNav_PricingUrl {
            get {
                return ResourceManager.GetString("SiteNav_PricingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string SiteNav_Support {
            get {
                return ResourceManager.GetString("SiteNav_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://supportone.componentone.com/login.
        /// </summary>
        public static string SiteNav_SupportUrl {
            get {
                return ResourceManager.GetString("SiteNav_SupportUrl", resourceCulture);
            }
        }
    }
}
