//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiExplorer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Visitor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Visitor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApiExplorer.Localization.Visitor", typeof(Visitor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .NET Core Visitor Web API collects user data such as IP, Geographical location, language, referring site, session, operating system, device, browser. It&apos;s useful for web developers to customize content for individual users.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no location information base on your ip address.
        /// </summary>
        public static string No_Location_Found {
            get {
                return ResourceManager.GetString("No_Location_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been browsing this site for.
        /// </summary>
        public static string Template_Browsing_Time {
            get {
                return ResourceManager.GetString("Template_Browsing_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device is running {0} version {1} on {2} {3} {4} bit.
        /// </summary>
        public static string Template_Device_Info {
            get {
                return ResourceManager.GetString("Template_Device_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your IP adress is.
        /// </summary>
        public static string Template_Ip_Address {
            get {
                return ResourceManager.GetString("Template_Ip_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You landed this site on {0}..
        /// </summary>
        public static string Template_Landed_Time {
            get {
                return ResourceManager.GetString("Template_Landed_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It has been {0} since your last visit.
        /// </summary>
        public static string Template_Last_Visit {
            get {
                return ResourceManager.GetString("Template_Last_Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re from {0}.
        /// </summary>
        public static string Template_Location_Info {
            get {
                return ResourceManager.GetString("Template_Location_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You visited this site {0} times..
        /// </summary>
        public static string Template_Total_Visits_Time {
            get {
                return ResourceManager.GetString("Template_Total_Visits_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VisitorAPI tell us that:.
        /// </summary>
        public static string Template_Visitor_Shown {
            get {
                return ResourceManager.GetString("Template_Visitor_Shown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You visited this site {0} times. Nice to see you again!.
        /// </summary>
        public static string Template_Visits_Time {
            get {
                return ResourceManager.GetString("Template_Visits_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days ago.
        /// </summary>
        public static string Time_Days_Ago {
            get {
                return ResourceManager.GetString("Time_Days_Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours ago.
        /// </summary>
        public static string Time_Hours_Ago {
            get {
                return ResourceManager.GetString("Time_Hours_Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        public static string Time_Just_Now {
            get {
                return ResourceManager.GetString("Time_Just_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes ago.
        /// </summary>
        public static string Time_Minutes_Ago {
            get {
                return ResourceManager.GetString("Time_Minutes_Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months_ago.
        /// </summary>
        public static string Time_Months_Ago {
            get {
                return ResourceManager.GetString("Time_Months_Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years_ago.
        /// </summary>
        public static string Time_Years_Ago {
            get {
                return ResourceManager.GetString("Time_Years_Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And much more.
        /// </summary>
        public static string Txt_Much_More {
            get {
                return ResourceManager.GetString("Txt_Much_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Overview.
        /// </summary>
        public static string Txt_Overview {
            get {
                return ResourceManager.GetString("Txt_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Browser.
        /// </summary>
        public static string Txt_Title_Browser {
            get {
                return ResourceManager.GetString("Txt_Title_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Mobile) Device.
        /// </summary>
        public static string Txt_Title_Device {
            get {
                return ResourceManager.GetString("Txt_Title_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First/Initial Session.
        /// </summary>
        public static string Txt_Title_First_Session {
            get {
                return ResourceManager.GetString("Txt_Title_First_Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geographical Location.
        /// </summary>
        public static string Txt_Title_Geo {
            get {
                return ResourceManager.GetString("Txt_Title_Geo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string Txt_Title_Ip {
            get {
                return ResourceManager.GetString("Txt_Title_Ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language/Locale.
        /// </summary>
        public static string Txt_Title_Locale {
            get {
                return ResourceManager.GetString("Txt_Title_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        public static string Txt_Title_Os {
            get {
                return ResourceManager.GetString("Txt_Title_Os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Session.
        /// </summary>
        public static string Txt_Title_Session {
            get {
                return ResourceManager.GetString("Txt_Title_Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Unique Visitor ID.
        /// </summary>
        public static string Txt_Title_Unique_VisitorId {
            get {
                return ResourceManager.GetString("Txt_Title_Unique_VisitorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Histories.
        /// </summary>
        public static string Txt_Title_Visitor_Visit_Histories {
            get {
                return ResourceManager.GetString("Txt_Title_Visitor_Visit_Histories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor ID.
        /// </summary>
        public static string Txt_Title_VisitorId {
            get {
                return ResourceManager.GetString("Txt_Title_VisitorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Variables.
        /// </summary>
        public static string Txt_Variables {
            get {
                return ResourceManager.GetString("Txt_Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Date.
        /// </summary>
        public static string Txt_Visit_Date {
            get {
                return ResourceManager.GetString("Txt_Visit_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to visitor api!.
        /// </summary>
        public static string Welcome_Message {
            get {
                return ResourceManager.GetString("Welcome_Message", resourceCulture);
            }
        }
    }
}
