//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiExplorer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Wijmo5Olap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Wijmo5Olap() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApiExplorer.Localization.Wijmo5Olap", typeof(Wijmo5Olap).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column totals.
        /// </summary>
        public static string Index_ColumnTotals {
            get {
                return ResourceManager.GetString("Index_ColumnTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset.
        /// </summary>
        public static string Index_Dataset {
            get {
                return ResourceManager.GetString("Index_Dataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row totals.
        /// </summary>
        public static string Index_RowTotals {
            get {
                return ResourceManager.GetString("Index_RowTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Zeros.
        /// </summary>
        public static string Index_ShowZeros {
            get {
                return ResourceManager.GetString("Index_ShowZeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this sample, all the data such as the field list in &lt;b&gt;PviotPanel&lt;/b&gt;, the aggregated data are shown in &lt;b&gt;PivotGrid&lt;/b&gt; and the detail raw data for some cells are fetched from the &lt;b&gt;DataEngine&lt;/b&gt; server api.
        ///        We also have a client-side option if you prefer..
        /// </summary>
        public static string Index_Text0 {
            get {
                return ResourceManager.GetString("Index_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this sample, the &lt;b&gt;PivotPanel&lt;/b&gt; control is bound with the &lt;b&gt;DataEngine&lt;/b&gt; api.
        ///        And the &lt;b&gt;PivotGrid&lt;/b&gt; control is used to show the aggregated data. When double clicking on some cells in the &lt;b&gt;PivotGrid&lt;/b&gt; control, a new grid will pop up to show the detail raw data for the cell..
        /// </summary>
        public static string Index_Text1 {
            get {
                return ResourceManager.GetString("Index_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of available fields will show in the &lt;b&gt;PivotPanel&lt;/b&gt;, and
        ///        users will be able to drag fields between summary areas to generate data summaries
        ///        (also known as &quot;views&quot;).
        ///        Users can also configure the fields by setting their headers, summary functions,
        ///        filters, and formats..
        /// </summary>
        public static string Index_Text2 {
            get {
                return ResourceManager.GetString("Index_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;PivotPanel&lt;/b&gt; control has properties that allow you to customize
        ///        the view. Use the controls below to modify the values of these properties
        ///        and see their effect:.
        /// </summary>
        public static string Index_Text3 {
            get {
                return ResourceManager.GetString("Index_Text3", resourceCulture);
            }
        }
    }
}
